#配置数据源
spring:
  datasource:
    username: root
    password: abcd+1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.66.52.108:3306/spring_transactional?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false